
---
- name: Selectively disable IPv6 on Red Hat systems using nmcli
  hosts: all
  become: yes
  tasks:
    - name: Get list of active connections with IPv6 enabled
      shell: |
        nmcli -t -f NAME,IP6 connection show --active | grep -v ':$' | cut -d':' -f1
      register: ipv6_active_connections
      changed_when: false
      failed_when: false

    - name: Disable IPv6 for connections with active IPv6
      command: nmcli connection modify "{{ item }}" ipv6.method ignore
      loop: "{{ ipv6_active_connections.stdout_lines }}"
      when: 
        - ipv6_active_connections.stdout_lines is defined
        - ipv6_active_connections.stdout_lines | length > 0
      register: ipv6_changes

    - name: Restart NetworkManager only if changes were made
      systemd:
        name: NetworkManager
        state: restarted
      when: ipv6_changes is changed

    - name: Verify IPv6 status for modified connections
      command: nmcli -t -f NAME,IP6 connection show --active
      register: final_ipv6_status
      changed_when: false
      when: ipv6_changes is changed

    - name: Display results
      debug:
        msg: "IPv6 disabled for {{ ipv6_changes.results | selectattr('changed') | list | length }} connections"
      when: ipv6_changes is defined
