---
- name: Disable IPv6 on active interfaces using nmcli
  hosts: all
  become: true
  tasks:
    - name: Get a list of active network interfaces
      command: nmcli -t -f device,state dev
      register: active_interfaces_output
      changed_when: false

    - name: Parse active interfaces
      set_fact:
        active_interfaces: "{{ active_interfaces_output.stdout_lines | select('search', 'connected') | map('regex_replace', '^(.*):.*', '\\1') | list }}"

    - name: Check if IPv6 is enabled on each active interface
      command: nmcli -f ipv6.method dev show {{ item }}
      register: ipv6_status
      loop: "{{ active_interfaces }}"
      changed_when: false
      ignore_errors: true

    - name: Disable IPv6 on interfaces where it is enabled
      command: nmcli con mod {{ item.item }} ipv6.method ignore
      loop: "{{ ipv6_status.results }}"
      when: "'ipv6.method: auto' in item.stdout or 'ipv6.method: link-local' in item.stdout"
      
    - name: Restart the network connection to apply changes
      command: nmcli con up {{ item.item }}
      loop: "{{ ipv6_status.results }}"
      when: "'ipv6.method: auto' in item.stdout or 'ipv6.method: link-local' in item.stdout"
