- hosts: localhost
  gather_facts: false
  vars:
    ansible_controller_host: "rhel8tower.theesway.org"
    ansible_controller_token: "bfI48EBFvdnWqqx8ztbvWX0rtn8UbT"
    aap_controller: "http://rhel8tower.theesway.org/"
    aap_username: "claude"
    aap_password: "N0aZ0eW!rld?"
    aap_main_project: "Proj_TowerRoles"
    aap_call_playbook: "teamcreation.yml"
    aap_template_name: "SurveyCreation"
    aap_main_inventory: "INV_VCenterDworp"

  tasks:
    - name: Get list of inventories from Ansible Controller
      uri:
        url: "http://{{ ansible_controller_host }}/api/v2/{{ item.kind }}/"
        method: GET
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ ansible_controller_token }}"
      register: response 
      loop:
        - {kind: 'inventories', listresult: 'inventory_response' }
        - {kind: 'credentials', listresult: 'credentials_response' }

    - name: Store the list of inventories in a variable
      set_fact:
        inventory_list: "{{ response.results[0].json | json_query('results[*].name') }}"
        cred_listfull: "{{ response.results[1].json | json_query('results[].{name: name, kind: credential_type}') }}"

    - name: Retrieving the MutualIT Ansible Controller token
      awx.awx.token:
        description: "MutualIT AAP Token"
        scope: "read"
        state: present
        controller_host: "{{ aap_controller}}"
        controller_username: "{{ aap_username }}"
        controller_password: "{{ aap_password}}"
 
    - name: Create job template
      awx.awx.job_template:
        name: "{{ aap_template_name }}"
        project: "{{ aap_main_project }}"
        playbook: "{{ aap_call_playbook }}"
        inventory: "{{ aap_main_inventory }}" 
        survey_enabled: true
        extra_vars: 
           aap_main_credentials: "{{ cred_listfull }}"
        survey_spec:
          name: "Application Deployment Survey"
          description: "Survey for application deployment"
          spec:
            - question_name: "Enter the department to map to a org"
              question_description: "Please provide the department name"
              required: true
              type: "text"
              variable: "survey_department"
            - question_name: "Enter the Azure DevOps environment"
              question_description: "Please provide the DevOps env:"
              required: false
              type: "text"
              variable: "survey_project"
            - question_name: "List of Inventories"
              question_description: "Choose the needed Inventories"
              variable: "survey_inventories"
              type: "multiselect"
              required: true
              choices: "{{ inventory_list | default(omit) }}"
              #default: "{{ inventory | default(omit) }}"
            - question_name: "List of Credentials"
              question_description: "Choose the needed Credentials"
              variable: "survey_credentials"
              type: "multiselect"
              required: true
              choices: "{{ cred_listfull | map(attribute='name') | list | default(omit) }}"
              #default: "{{ credentials | default(omit) }}"
        controller_host: "{{ aap_controller }}"
        controller_username: "{{ aap_username }}"
        controller_password: "{{ aap_password }}"
