---
- name: Puppet migration - Extra packages
  debug:
    msg: "Puppet migration - Extra packages"

- include_vars: vars_packages.yml

- name: RHEL 8 common packages installation
  package:
    name: "{{ item }}"
    state: present
    enablerepo: "{{ RHEL8_REPOSCOMMON }}"
  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '8'
  loop: "{{ RHEL8_COMMON }}"

- name: RHEL8 PPC packages installation
  package:
    name: "{{ item }}"
    state: present
    enablerepo: "{{ RHEL8_REPOSPPC }}"
  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '8' and ansible_architecture == 'ppc64le'
  changed_when: false
  loop: "{{ RHEL8_PPC }}"
