---
- name: Puppet migration - CyberArk user/group part
  debug:
    msg: "Puppet migration - CyberArk user/group part"

- include_vars: vars.yml

- name: Check server environment
  set_fact:
    is_production: true
  when: inventory_hostname[4:6] == 'lp'
  changed_when: false
  failed_when: false

- name: Add CyberArk group (Production)
  group:
    name: "{{ CYBERARK_GROUP }}"
    gid: "{{ CYBERARK_GROUPID }}"
  when: is_production
  notify: stop_sssd

- name: Add CyberArk user (Production)
  user:
    name: "{{ CYBERARK_USER }}"
    comment: "Cyber Ark - Reconciliation Account Local - Must be able to reset pass phrases - Production"
    home: "/home/{{ CYBERARK_USER }}"
    password: "{{ CYBERARK_PASS }}"
    shell: /bin/bash
    uid: "{{ CYBERARK_USERID }}"
    group: "{{ CYBERARK_GROUP }}"
  when: is_production
  notify: stop_sssd

- name: Start sssd
  systemd:
    name: sssd
    state: "{{ item }}"
  when: is_production
  loop:
    - started
    - reloaded
  changed_when: false

