---
- name: Puppet migration - CyberArk user/group part

- include_vars: vars.yml

- name: Check server environment
  set_fact:
    is_production: true
  when: inventory_hostname[4:6] == 'lp'
  changed_when: false
  failed_when: false

- name: Add CyberArk group (Production)
  group:
    name: CyberArk
    gid: "{{ CYBERARK_GROUPID }}"
  when: is_production
  notify: Stop sssd

- name: Add CyberArk user (Production)
  user:
    name: "{{ CYBERARK_USER }}"
    comment: "Cyber Ark - Reconciliation Account Local - Must be able to reset pass phrases - Production"
    home: "/home/{{ CYBERARK_USER }}"
    password: "{{ CYBERARK_PASS }}"
    shell: /bin/bash
    uid: "{{ CYBERARK_USERID }}"
    gid: "{{ CYBERARK_GROUPID }}"
    manage_home: true
  when: is_production
  notify: Stop sssd

- name: Stop sssd
  command: "systemctl stop sssd && sss_cache -E"
  when: is_production
  register: sssd_stop_output
  changed_when: sssd_stop_output.stdout.find('Stopping sssd') != -1
  failed_when: false

- name: Start sssd
  systemd:
    name: sssd
    state: "{{ item }}"
  when: is_production
  loop:
    - started
    - reloaded
  changed_when: false

